image: node:alpine

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test
  - code_quality

build:
  stage: build
  script:
    - yarn install
  only:
    - merge_requests
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - 'node_modules/'
      - 'packages/*/dist/'
      - 'packages/*/node_modules/'

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - build
  script:
    - yarn test:ci
  only:
    - merge_requests
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
      cobertura: coverage/cobertura-coverage.xml

code_quality:
  stage: code_quality
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run code quality job in merge request pipelines
